# Generated by Django 6.0.7 on 2026-07-17 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fit_score', models.IntegerField()),
                ('reasoning', models.TextField(blank=True)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='jobs.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='profiles.profile')),
            ],
            options={
                'unique_together': {('profile', 'job')},
            },
        ),
    ]
