# Generated by Django 6.0.7 on 2026-07-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='doc_type',
            field=models.CharField(choices=[('tailored_resume', 'Tailored Resume'), ('cover_letter', 'Cover Letter'), ('interview_prep', 'Interview Prep'), ('roadmap', 'Roadmap'), ('skill_gap', 'Skill Gap')], max_length=30),
        ),
    ]
